import { chromium } from 'playwright';
import fs from 'fs';

const BASE=process.env.QA_BASE_URL||'http://127.0.0.1:8000';
const customRoutes=[
 ['01.01','/campaign/act-01/01-01-system-layers.html'],['01.02','/campaign/act-01/01-02-command-evidence.html'],['01.03','/campaign/act-01/01-03-trace-broken.html'],['01.04','/campaign/act-01/01-04-build-architecture.html'],['01.05','/campaign/act-01/01-05-coupled-failure.html'],['01.06','/campaign/act-01/01-06-architecture-gate.html'],['02.01','/campaign/act-02/02-01-frames-poses.html'],['02.02','/campaign/act-02/02-02-joint-axes.html'],['02.03','/campaign/act-02/02-03-forward-inverse-kinematics.html']
];
const batchIds=[];for(let a=2;a<=10;a++)for(let m=(a===2?4:1);m<=6;m++)batchIds.push(`${String(a).padStart(2,'0')}.${String(m).padStart(2,'0')}`);

function evalExpr(expr,s){return Function('s',`with(s){const abs=Math.abs,min=Math.min,max=Math.max,sqrt=Math.sqrt,sin=Math.sin,cos=Math.cos,exp=Math.exp,pi=Math.PI;return (${expr});}`)(s)}
function valsFor(c){if(c.kind==='select')return c.options.map(o=>o.value);const out=new Set([c.min,c.base,c.max]);for(let i=1;i<20;i++){const raw=c.min+(c.max-c.min)*i/20;const v=Math.min(c.max,Math.max(c.min,c.min+Math.round((raw-c.min)/c.step)*c.step));out.add(Number(v.toFixed(10)))}return[...out]}
function findCombo(m,expr,overrides={},want=true,differentFrom=null){const s={};for(const c of m.conditions||[])s[c.key]=c.value;Object.assign(s,overrides);const cs=m.controls||[],grids=cs.map(valsFor);let found=null,tries=0;function rec(i){if(found||tries>90000)return;if(i===cs.length){tries++;let ok=false;try{ok=!!evalExpr(expr,s)===want}catch{return}if(!ok)return;if(differentFrom&&!cs.some(c=>String(s[c.key])!==String(differentFrom[c.key])))return;found={};for(const c of cs)found[c.key]=s[c.key];return}for(const v of grids[i]){s[cs[i].key]=v;rec(i+1);if(found)return}}rec(0);return found}
function relevantKeys(m,expr){return(m.controls||[]).map(c=>c.key).filter(k=>new RegExp(`\\b${k}\\b`).test(expr||''))}
async function setControl(page,c,val){if(c.kind==='select'){await page.locator(`.choice-buttons button[data-key="${c.key}"][data-value="${String(val)}"]`).click()}else await page.locator(`#controls input[data-key="${c.key}"]`).evaluate((el,v)=>{el.value=String(v);el.dispatchEvent(new Event('input',{bubbles:true}))},val)}
async function currentControl(page,c){if(c.kind==='select'){const sel=page.locator(`.choice-buttons button[data-key="${c.key}"].selected`);return await sel.count()?await sel.getAttribute('data-value'):c.base}return Number(await page.locator(`#controls input[data-key="${c.key}"]`).inputValue())}
async function exerciseKey(page,c,start){if(c.kind==='select'){const alt=c.options.find(o=>String(o.value)!==String(start))?.value;if(alt!==undefined)await setControl(page,c,alt)}else{const span=c.max-c.min,alt=Math.abs(Number(start)-c.min)>span*.08?c.min:c.max;await setControl(page,c,alt)}}
async function dragRanges(page){const ranges=page.locator('input[type="range"]');const total=await ranges.count(),issues=[];let tested=0;for(let i=0;i<total;i++){const r=ranges.nth(i);if(!await r.isVisible()||!await r.isEnabled())continue;tested++;const before=Number(await r.inputValue()),min=Number(await r.getAttribute('min')),max=Number(await r.getAttribute('max')),box=await r.boundingBox();if(!box||box.width<20){issues.push(`range ${i}: no usable bounding box`);continue}const handle=await r.elementHandle();await handle.evaluate(el=>{el.dataset.qa3Events='0';el.addEventListener('input',()=>el.dataset.qa3Events=String(Number(el.dataset.qa3Events||0)+1),{once:false})});const p=(before-min)/Math.max(1e-9,max-min),startX=box.x+box.width*Math.max(.03,Math.min(.97,p)),targetP=p>.5?.12:.88,targetX=box.x+box.width*targetP,y=box.y+box.height/2;await page.mouse.move(startX,y);await page.mouse.down();await page.mouse.move(targetX,y,{steps:14});const connected=await handle.evaluate(el=>el.isConnected),events=Number(await handle.evaluate(el=>el.dataset.qa3Events||0));await page.mouse.up();const after=Number(await r.inputValue().catch(()=>NaN));if(!connected)issues.push(`range ${i}: DOM node replaced during drag`);if(!events||!Number.isFinite(after)||Math.abs(after-before)<Math.max(1e-9,(max-min)*.02))issues.push(`range ${i}: click-hold-drag did not produce a meaningful change (${before} -> ${after}, events ${events})`)}return{total,tested,issues}}
async function baseChecks(page){const issues=[];const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);if(overflow>4)issues.push(`horizontal overflow ${overflow}px at 1440px viewport`);const start=page.locator('#startBtn');if(await start.count()&&await start.isVisible())await start.click();await page.waitForTimeout(80);return issues}
async function reopen(page,url){await page.goto(url,{waitUntil:'networkidle',timeout:20000});const s=page.locator('#startBtn');if(await s.count()&&await s.isVisible())await s.click();await page.waitForTimeout(50)}
async function testCustom(browser,id,route){const page=await browser.newPage({viewport:{width:1440,height:1000}}),js=[];page.on('pageerror',e=>js.push(String(e)));page.on('console',m=>{if(m.type()==='error')js.push(m.text())});const r={id,kind:'custom',status:'PASS',issues:[]},url=BASE+route;try{const resp=await page.goto(url,{waitUntil:'networkidle',timeout:20000});if(!resp||!resp.ok())r.issues.push(`HTTP ${resp?.status()}`);r.issues.push(...await baseChecks(page));const drag=await dragRanges(page);r.rangeCount=drag.total;r.rangeTested=drag.tested;r.issues.push(...drag.issues);if(js.length)r.issues.push(...js.map(x=>'JS: '+x))}catch(e){r.issues.push('EXCEPTION: '+e.message)}if(r.issues.length)r.status=r.issues.some(x=>/HTTP|EXCEPTION|JS:|DOM node replaced|click-hold-drag/.test(x))?'BLOCKER':'MINOR';await page.close();return r}
async function testBatch(browser,id,m){const page=await browser.newPage({viewport:{width:1440,height:1000}}),js=[];page.on('pageerror',e=>js.push(String(e)));page.on('console',m=>{if(m.type()==='error')js.push(m.text())});const r={id,kind:'batch',status:'PASS',issues:[],phases:[]},url=`${BASE}/campaign/mission.html?m=${id}`;try{const resp=await page.goto(url,{waitUntil:'networkidle',timeout:20000});if(!resp||!resp.ok())r.issues.push(`HTTP ${resp?.status()}`);r.issues.push(...await baseChecks(page));if(!await page.locator('#game').isVisible())r.issues.push('game did not open');if(!await page.locator('#conditions').count()||!await page.locator('#controls').count())r.issues.push('world/control separation missing');const drag=await dragRanges(page);r.rangeCount=drag.total;r.rangeTested=drag.tested;r.issues.push(...drag.issues);
    // Reload so slider probing cannot contaminate mission state.
    await reopen(page,url);const main=page.locator('#mainAction');
    if(m.gateCases){const cond={};for(const c of m.conditions||[])cond[c.key]=c.value;for(let gi=0;gi<m.gateCases.length;gi++){const g=m.gateCases[gi];Object.assign(cond,g.set||{});const fail=findCombo(m,g.goal,cond,false),pass=findCombo(m,g.goal,cond,true);if(!fail||!pass){r.issues.push(`gate ${gi+1}: browser solver missing fail/pass`);break}for(const c of m.controls)if(c.key in fail)await setControl(page,c,fail[c.key]);for(const k of relevantKeys(m,g.goal)){const c=m.controls.find(x=>x.key===k);if(c)await exerciseKey(page,c,fail[k])}for(const c of m.controls)if(c.key in pass)await setControl(page,c,pass[c.key]);if(!await main.isEnabled())r.issues.push(`gate ${gi+1}: soft-lock after fail→pass`);else{await main.click();await page.locator('#reflectionContinue').click();r.phases.push(`GATE${gi+1}`)}}
    }else{
      // Explore all decisions first.
      for(const c of m.controls||[]){if(c.kind==='select'){const opts=c.exploreAll?c.options:c.options.slice(0,Math.min(2,c.options.length));for(const o of opts)await setControl(page,c,o.value)}else{await setControl(page,c,c.min);await setControl(page,c,c.max)}}
      if(!await main.isEnabled())r.issues.push('EXPLORE soft-lock after all controls exercised');else{await main.click();await page.locator('#reflectionContinue').click();r.phases.push('EXPLORE')}
      const fail=findCombo(m,m.goal,{},false),pass=findCombo(m,m.goal,{},true);if(!fail||!pass)r.issues.push('APPLY browser solver missing fail/pass');else{for(const c of m.controls)if(c.key in fail)await setControl(page,c,fail[c.key]);for(const k of relevantKeys(m,m.goal)){const c=m.controls.find(x=>x.key===k);if(c)await exerciseKey(page,c,fail[k])}for(const c of m.controls)if(c.key in pass)await setControl(page,c,pass[c.key]);if(!await main.isEnabled())r.issues.push('APPLY soft-lock after fail→pass');else{await main.click();if(m.disturbance)await page.locator('#reflectionContinue').click();r.phases.push('APPLY')}}
      if(m.disturbance&&m.transferGoal){const phaseStart={};for(const c of m.controls)phaseStart[c.key]=await currentControl(page,c);const passT=findCombo(m,m.transferGoal,m.disturbance.set||{},true,phaseStart)||findCombo(m,m.transferGoal,m.disturbance.set||{},true);if(!passT)r.issues.push('TRANSFER browser solver missing pass');else{for(const k of relevantKeys(m,m.transferGoal)){const c=m.controls.find(x=>x.key===k);if(c)await exerciseKey(page,c,phaseStart[k])}for(const c of m.controls)if(c.key in passT)await setControl(page,c,passT[c.key]);if(!await main.isEnabled())r.issues.push('TRANSFER soft-lock after adaptation');else{await main.click();r.phases.push('TRANSFER')}}}
    }
    if(js.length)r.issues.push(...js.map(x=>'JS: '+x));
  }catch(e){r.issues.push('EXCEPTION: '+e.message)}if(r.issues.length)r.status=r.issues.some(x=>/HTTP|EXCEPTION|JS:|soft-lock|DOM node replaced|click-hold-drag|missing/.test(x))?'BLOCKER':'MINOR';await page.close();return r}

const browser=await chromium.launch({headless:true}),results=[];for(const [id,route] of customRoutes){console.log('QA3 custom',id);results.push(await testCustom(browser,id,route))}for(const id of batchIds){const act=id.split('.')[0],d=JSON.parse(fs.readFileSync(`data/missions-act-${act}.json`,'utf8')),m=d.missions.find(x=>x.id===id);results.push(m?await testBatch(browser,id,m):{id,kind:'batch',status:'BLOCKER',issues:['mission definition missing']})}await browser.close();const summary={total:results.length,pass:results.filter(x=>x.status==='PASS').length,minor:results.filter(x=>x.status==='MINOR').length,blocker:results.filter(x=>x.status==='BLOCKER').length};fs.writeFileSync('qa3-browser-results.json',JSON.stringify({summary,results},null,2));let md=`# QA3 Browser Interaction Report\n\nTotal **${summary.total}** · PASS **${summary.pass}** · MINOR **${summary.minor}** · BLOCKER **${summary.blocker}**\n\n| Mission | Kind | Status | Range total/tested | Issues |\n|---|---|---:|---:|---|\n`;for(const x of results)md+=`| ${x.id} | ${x.kind} | ${x.status} | ${x.rangeCount??0}/${x.rangeTested??0} | ${(x.issues||[]).join('; ').replace(/\|/g,'/')} |\n`;fs.writeFileSync('qa3-browser-results.md',md);console.log(summary);if(summary.blocker)process.exitCode=1;
